## NumPy Tutorial

NumPy is a module for Python. The name is an acronym for "Numeric Python" or "Numerical Python".
It is an extension module for Python, mostly written in C. This makes sure that the precompiled 
mathematical and numerical functions and functionalities of Numpy guarantee great execution 
speed.

to install : pip install numpy

In [2]:
# import csv
# with open('winequality-red.csv', 'r') as f:
#     wines = list(csv.reader(f, delimiter=';'))
# #print(wines)

# # l = []
# # with open('winequality-red.csv') as f:

# #     for line in f.readlines():
# #         l.append(line.strip().split(';'))
        
# # l

# q = [float(wine[-1]) for wine in wines[1:]]
# avg = sum(q)/len(q)
# avg
    

In [23]:
import numpy as np
# print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolut

# Array
Numpy array is a powerful N-dimensional array object which is in the form of rows and columns.
We can initialize numpy arrays from nested Python lists and access it elements.

# Python NumPy Array v/s List
We use python numpy array instead of a list because of the below three reasons:
1. Less Memory
2. Fast
3. Convenient

In [36]:
cvalues = [20.1, 20, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]

AttributeError: 'list' object has no attribute 'dtypes'

In [43]:
c_arr = np.array(cvalues)
c_arr.dtype

dtype('float64')

In [11]:
print(dir(c_arr))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [13]:
c_arr

array([20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1])

In [14]:
f_arr = c_arr * 9/5 + 32
# f_arr = [ x*9/5 + 32 for x in cvalues] 

In [15]:
f_arr

array([68.18, 69.44, 71.42, 72.5 , 72.86, 72.14, 71.24, 70.16, 69.62,
       68.18])

In [16]:
type(c_arr)

numpy.ndarray

# Multi-dimensional Array

In [28]:
a=np.array([(1,8,3),(4,5,6),(2,5,7)])
# list -> a[0][2]->3
# a[0,2] 
a[:,:]

array([[1, 8, 3],
       [4, 5, 6],
       [2, 5, 7]])

In [22]:
# Here the rows are called as axis 1 and the columns are called as axis 0.
a.sum(axis=0)

array([5, 7, 9])

In [55]:
# print(np.sqrt(a))
print(np.std(a, axis=0))
print(np.mean(a, axis=0))
print(np.median(a, axis=0))
# print(np.mod(a, axis=0))

[1.24721913 1.41421356 1.69967317]
[2.33333333 6.         5.33333333]
[2. 5. 6.]


In [46]:
# additional operation
x= np.array([(2,2,3),(3,4,5)])
y= np.array([(1.5,2,3),(3,4,5)])
print(x-y)
print(x*y)
print(x/y)
# print(y.dtype)

[[0.5 0.  0. ]
 [0.  0.  0. ]]
[[ 3.  4.  9.]
 [ 9. 16. 25.]]
[[1.33333333 1.         1.        ]
 [1.         1.         1.        ]]
float64


# more info
https://cs231n.github.io/python-numpy-tutorial/

https://www.dataquest.io/blog/numpy-tutorial-python/

In [48]:
wines = np.genfromtxt("winequality-red.csv", delimiter=";", skip_header=1)

In [58]:
qualities = wines[:,-1]

5.6360225140712945

In [60]:
np.mean(wines,axis=0)

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311,  5.63602251])

In [63]:
np.std(wines,axis=0)

array([1.74055180e+00, 1.79003704e-01, 1.94740214e-01, 1.40948711e+00,
       4.70505826e-02, 1.04568856e+01, 3.28850367e+01, 1.88674370e-03,
       1.54338181e-01, 1.69453967e-01, 1.06533430e+00, 8.07316877e-01])

In [64]:
np.median(wines,axis=0)

array([ 7.9    ,  0.52   ,  0.26   ,  2.2    ,  0.079  , 14.     ,
       38.     ,  0.99675,  3.31   ,  0.62   , 10.2    ,  6.     ])

In [22]:
wines[0:3,3]

array([1.9, 2.6, 2.3])

In [23]:
wines[3,:]

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,  6.   ])

In [24]:
w = wines[:,11] * 2

array([10., 10., 10., ..., 12., 10., 12.])

In [25]:
wines[:,11] + wines[:,11]

array([10., 10., 10., ..., 12., 10., 12.])